---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: localhost
  roles_path: ../
  require_ansible_repo: false
  require_ansible_omnibus: false
  require_ansible_source: false
  require_pip: true
  ansible_version: 2.4.3.0
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>
  no_proxy: localhost,127.0.0.1
  ignore_extensions_from_root: [".git",".idea",".kitchen.yml"]
  ignore_paths_from_root: [".git",".idea",".kitchen"]
  <% if ENV['VERSION'] %>
  attributes:
    extra_vars:
      es_major_version: "<%= ENV['VERSION'] %>"
      <% if ENV['VERSION'] == '5.x' %>
      es_version: '5.6.7'
      <% end %>
  <% end %>

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - git: https://github.com/elastic/elasticsearch-inspec.git
      branch: 6.0
  attributes:
    es_service_name: security_node_elasticsearch
    elasticsearch_conf: /etc/elasticsearch/security_node/elasticsearch.yml
    ssl_param: true
    es_pass: elasticChanged
    elastic_ip: localhost
    es_logs_dir: /var/log/elasticsearch/localhost-security_node
  format: json
  output: ./%{platform}_%{suite}_results.json

transport:
  max_ssh_sessions: 6

platforms:
- name: centos-7
  driver:
    vagrantfiles:
      - /test/Vagrantfile_setup.rb
    name: vagrant
    box: bento/centos-7
    provision: true
    pre_create_command: cp <%=ENV['ES_XPACK_LICENSE_FILE']%> {{vagrant_root}}

suites:
  - name: standard
    provisioner:
      idempotency_test: true
      playbook: test/integration/standard.yml
    run_list:
    attributes:
  - name: package
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/package.yml
  - name: config
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/config.yml
  - name: multi
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/multi.yml
      idempotency_test: true
  - name: xpack
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/xpack.yml
  - name: xpack-standard
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/xpack-standard.yml
      idempotency_test: true
  - name: xpack-stig
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/xpack-stig.yml
  - name: issue-test
    run_list:
    attributes:
    provisioner:
      playbook: test/integration/issue-test.yml
      idempotency_test: false
